apiVersion: v1
kind: Service
metadata:
  namespace: mynamespace
  name: jenkins-svc
spec:
  type: LoadBalancer 
  selector:
    app: jenkins
  ports:  
  - name: "http"
    port: 80
    targetPort: 8080
    protocol: "TCP"
  - name: "slave"
    port: 50000
    targetPort: 50000
    protocol: "TCP"
